### ISSUE TITLE
Add Table of Contents and display it on the right of a post

### ISSUE THREAD

**Issue by prrao87** [kuzudb/blog#7]
When reading blogs on a wide screen, it helps to have a table of contents that's placed to the right side of the post (just like we did in Docusaurus). Astro provides the rehype plugin that [generates a ToC](https://destiner.io/blog/post/using-markdown-plugins-in-astro). Once the ToC is generated for each post, some CSS tweaks may be necessary to get the appearance right on both wide screens and mobile devices.

**Comment by mewim** [comment]
Added a ToC similar to docusaurus in #16: 
<img width="2032" alt="Screenshot 2024-03-05 at 5 59 57 PM" src="https://github.com/kuzudb/blog/assets/14037726/2d0107e1-3b1a-4793-b7f4-a29855de2e58">

The current behavior is to hide it on smaller screens (with width <= 1280px) similar to docusaurus. If the desired behavior is to show ToC on top of the content, it could be achieved by commenting out:
https://github.com/kuzudb/blog/blob/c8c615287009cef7fc372b7350e13a44843ae81d/src/styles/global.css#L171-L173

and uncommenting:
https://github.com/kuzudb/blog/blob/c8c615287009cef7fc372b7350e13a44843ae81d/src/styles/global.css#L162-L168

**Comment by prrao87** [comment]
This is good, let's keep this behaviour (no ToC on small screens) for now. Thanks!
